openapi: 3.0.0
info:
  title: API Documentation
  description: API documentation using Swagger YAML file
  version: 1.0.0
servers:
  - url: /api
    description: 'description'

# Define tags section
tags:
  - name: Users
    description: Operations related to user management

paths:
  /users:
    get:
      tags:
        - Users
      summary: Get all users
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
        '500':
          description: Server error
    post:
      summary: Create a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        201:
          description: User created
